### ISSUE TITLE
Use stone to auto generate functions and data types

### ISSUE THREAD

**Issue by braincore** [sger/elixir_dropbox#1]
We use a tool called [Stone](https://github.com/dropbox/stone) to automatically generate large portions of our Dropbox SDKs from these [specs](https://github.com/dropbox/dropbox-api-spec). It would be great if this library could use Stone as well, which has an upfront cost, but really reduces maintenance burden. See the [Dropbox Python SDK](https://github.com/dropbox/dropbox-sdk-python) for an example.

**Comment by sger** [comment]
thanks for the advice @braincore
