### ISSUE TITLE
Introduce something like exvcr

### ISSUE THREAD

**Issue by jespr** [sger/elixir_dropbox#2]
Hi :)

Are you OK with me taking a stab at introducing something like `exvcr` so we don't have to hit Dropbox every single time we run tests? :)

**Comment by sger** [comment]
@jespr absolutely

**Comment by sger** [comment]
@jespr added exvcr

**Comment by jespr** [comment]
You beat me to it! I'm in Greece at the moment :) leaving tomorrow though :/ thanks for doing that
